branch-defaults:
  default:
    environment: tifanaga
    group_suffix: null
deploy:
  artifact: Archive.zip
environment-defaults:
  tifanaga:
    branch: null
    repository: null
global:
  application_name: assdddaaa
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: fullstackuser
  repository: null
  sc: null
  workspace_type: Application
